# variables/dev.yml
# Variables for the Development environment

variables:
  gcpServiceAccountKeyFile: "ado-bq-exporter-key-dev.json"
  gcpProjectId: "pkrb12-dev"
  bqDataset: "retail_data_dev"
  productBranchId: "default_branch"
  productTableIdPrefix: "products_export_view"
  userEventTableIdPrefix: "user_events_export_view"
